#!/bin/sh
# Layer 1 (menu UX only): tell GRUB that CachyOS holds a hibernation image.
GRUBENV=/boot/grub/grubenv

case "$1:$2" in
    pre:hibernate|pre:hybrid-sleep|pre:suspend-then-hibernate)
        grub-editenv "$GRUBENV" set cachyos_hib=yes && sync
        ;;
    post:hibernate|post:hybrid-sleep|post:suspend-then-hibernate)
        grub-editenv "$GRUBENV" unset cachyos_hib && sync
        ;;
esac
exit 0
