$font = JetBrainsMonoNerdFontMono

background {
    path = ~/.config/backgrounds/current
    contrast = 0.8916
    brightness = 0.8916
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}

label {
    text = $TIME
    text_align = center
    color = rgba(235, 219, 178, 1)
    font_size = 40
    font_family = $font
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    font_family = $font
    placeholder_text = <i><span foreground="##EBDBB2">🔒  Enter Pass</span></i>
    position = 0, -200
    halign = center
    valign = center
}
