# smalltop -- Samsung Galaxy Book 3 Pro (NP960XFG-KC2IT, board P07RGU).
#
# Written by hand against hardware that was inspected live, not generated by
# nixos-generate-config. The previous version of this file described a
# different, now-dead machine (ext4 on LUKS, no swap); only the userspace
# intent survived.
#
# Hardware facts this file is written against (all verified on the machine):
#   CPU      i7-1360P (Raptor Lake-P, 4P+8E)        -> kvm-intel
#   RAM      16 GB LPDDR5, soldered                  -> 20 GiB swap, hibernation
#   Disk     Kingston NV2 SM2267XT, DRAM-less        -> see ./disko.nix
#   GPU      Intel Iris Xe [8086:a7a0]               -> i915 (xe is present but
#                                                       i915 is what binds)
#   WiFi     Intel CNVi [8086:51f1], iface wlo1      -> iwlwifi. NO ETHERNET.
#   Audio    SOF cAVS [8086:51ca] + Realtek ALC298   -> see the audio section
#   Camera   Intel IPU6 + ov02c10 via int3472        -> see the camera section
#   Other    Thunderbolt 4 / USB4, TPM 2.0, Secure Boot disabled
{
  config,
  lib,
  pkgs,
  inputs,
  modulesPath,
  ...
}:

let
  # Things that live on the shared @nomad subvolume but need to appear in
  # maddev's home directory. Adding another one later is a single line here plus
  # `mv` of the directory -- deliberately NOT a change to the disk layout.
  #
  # @nomad IS DATA ONLY. This is the governing architectural decision, made by
  # the user, and it is the reason the list below looks conservative:
  #
  #   Userspace is deliberately NOT shared between NixOS and CachyOS. Each
  #   distro gets its own browser profile, its own Steam install, its own
  #   application state -- everything that is not plain data. Sharing
  #   application state is what manufactures version-skew hazards; not sharing
  #   it dissolves that entire class of problem instead of managing it.
  #
  # So the test for adding something here is: "is this DATA, or is this an
  # application's STATE?" Data goes on @nomad. State does not, however
  # convenient it looks.
  #
  # To add one: add a line here, `mv` the directory into /nomad/maddev/, and
  # rebuild. That is the whole operation. Nothing in ./disko.nix changes, no
  # subvolume is created, no partition is touched -- @nomad is one btrfs
  # subvolume and these are plain directories inside it. The fileSystems
  # entries and the systemd-tmpfiles rules below both generate from this
  # attrset, so they grow automatically.
  #
  # DELIBERATELY EXCLUDED -- DO NOT "helpfully" ADD THESE:
  #   ~/.config/zen   Was approved earlier, then WITHDRAWN. Zen is application
  #                   state, not data; each distro keeps its own profile.
  #   ~/Development   Stays on @home, NixOS-side only. Explicit user decision.
  #   Steam library   Not shared at all. See CACHYOS.md.
  # None of these are oversights. If one looks like an obvious omission to you,
  # that is precisely why this comment exists.
  #
  # Still to come: "some repos", which the user has not yet named.
  nomadBinds = {
    "/home/maddev/Downloads" = "/nomad/maddev/Downloads";
    "/home/maddev/Documents" = "/nomad/maddev/Documents";
    "/home/maddev/Knowledge" = "/nomad/maddev/Knowledge";
  };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.disko.nixosModules.disko
    ./disko.nix
    ../../modules/lan-discovery.nix
    ../../modules/ghostty-terminfo.nix
  ];

  networking.hostName = "smalltop";
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # ---------------------------------------------------------------------------
  # Kernel
  # ---------------------------------------------------------------------------
  # The shared ../../configuration.nix pins pkgs.linuxPackages_6_12. That is
  # BELOW the floor for this machine: the samsung_galaxybook platform driver
  # (keyboard backlight, performance modes, battery charge limit) was merged in
  # 6.15 -- NOT 6.14, which is the floor of the *out-of-tree* driver and is the
  # number most write-ups quote. Without it none of the Samsung-specific
  # hardware exists at all.
  # mkForce is required -- a bare re-declaration would collide with the shared
  # definition rather than replace it.
  #
  # 6.18 rather than latest: it is what the machine is running today (6.18.51,
  # observed), so the hardware behaviour below is measured rather than assumed.
  # Note that nixpkgs 26.05 has REMOVED linuxPackages_6_17 and _6_19 (EOL
  # upstream) -- pinning either will fail to evaluate.
  boot.kernelPackages = lib.mkForce pkgs.linuxPackages_6_18;

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd" # harmless if the BIOS is not in VMD/RST mode
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # ---------------------------------------------------------------------------
  # Boot loader
  # ---------------------------------------------------------------------------
  # GRUB itself (efiSupport, device = "nodev", systemd-boot disabled) is set in
  # the shared ../../configuration.nix. Only the host-specific bits belong here.
  #
  # useOSProber is what will eventually find CachyOS. It is scoped to this host
  # ON PURPOSE -- it must never leak into the shared file, where it would run
  # against the wrong disks on bigsys/elder/nomad/razor.
  boot.loader.grub.useOSProber = true;
  boot.loader.efi.efiSysMountPoint = "/boot";

  # ---------------------------------------------------------------------------
  # Hibernation
  # ---------------------------------------------------------------------------
  # boot.resumeDevice is NOT set here. ./disko.nix declares the swap logical
  # volume with `resumeDevice = true`, and disko emits
  #     boot.resumeDevice = "/dev/smalltop/swap"
  # which is the DECRYPTED device inside the LUKS container -- the only thing
  # the kernel can actually resume from. Setting it a second time here would
  # just be a conflicting definition.
  #
  # The resume= kernel parameter is added automatically by the systemd-initrd
  # module from boot.resumeDevice, and the shared configuration.nix already
  # sets boot.initrd.systemd.enable = true, so the LUKS container and the LVM
  # volume group are both available before the resume attempt.
  #
  # DANGER: /dev/smalltop/cachyos-swap exists and is deliberately NOT referenced
  # anywhere in this configuration. If NixOS and CachyOS ever share one swap
  # device, booting one while the other is hibernated destroys the image (and
  # very likely the filesystem it was about to write back). See ./CACHYOS.md.

  # ---------------------------------------------------------------------------
  # Graphics -- Intel Iris Xe (Raptor Lake-P)
  # ---------------------------------------------------------------------------
  # i915 is what actually binds to 8086:a7a0 on 6.18; the xe module is present
  # but does not claim this generation. Nothing needs forcing.
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      intel-media-driver # VA-API for Gen9+ (iHD)
      vpl-gpu-rt # oneVPL runtime, hardware encode
      libvdpau-va-gl
    ];
  };
  environment.sessionVariables.LIBVA_DRIVER_NAME = "iHD";

  # ---------------------------------------------------------------------------
  # WiFi -- Intel CNVi, interface wlo1. This machine has NO ethernet port.
  # ---------------------------------------------------------------------------
  # The regulatory domain on the target was observed as "00" (world), which is
  # the most restrictive setting and costs channels and transmit power. The user
  # is in Spain (TZ Europe/Madrid).
  hardware.wirelessRegulatoryDatabase = true;
  boot.extraModprobeConfig = ''
    options cfg80211 ieee80211_regdom="ES"
  '';

  networking.useDHCP = lib.mkDefault true;

  # ---------------------------------------------------------------------------
  # Audio -- SOF + Realtek ALC298
  # ---------------------------------------------------------------------------
  # Observed on the machine: card "sofhdadsp", codec ALC298, subsystem ID
  # 144d:c886, topology sof-hda-generic-2ch.tplg, machine driver
  # skl_hda_dsp_generic. Pin 0x17 is [Fixed] Speaker with an EAPD bit.
  #
  # The Galaxy Book family drives its speakers from four class-D amplifiers
  # INSIDE the ALC298 (NIDs 0x38/0x39/0x3C/0x3D) which stay powered down until a
  # vendor COEF init sequence is written. There is no external amp, no CS35L41,
  # no _DSD firmware and no snd-intel-dspcfg involvement -- most of the advice
  # you will find online is for a different machine.
  #
  # NOTHING IS NEEDED HERE. I checked the quirk table in the 6.18 source
  # (sound/hda/codecs/realtek/alc269.c:6903):
  #
  #   SND_PCI_QUIRK(0x144d, 0xc886, "Samsung Galaxy Book3 Pro (NP964XFG)",
  #                 ALC298_FIXUP_SAMSUNG_AMP_V2_4_AMPS),
  #
  # 144d:c886 is exactly this machine's subsystem ID (observed in
  # /proc/asound/card0/codec#0). The quirk has been upstream since 6.12. The
  # Arch/Fedora hda-verb scripts that turn up in searches predate it.
  #
  # Still worth a listen after install. If the speakers ARE silent, the fix is a
  # module option rather than anything structural -- fold this into the
  # boot.extraModprobeConfig block above (it is one string, so keep the cfg80211
  # line):
  #
  #   options snd-hda-intel model=alc298-samsung-amp-v2-4-amps
  #
  # Do NOT apply the `dsp_driver=3` microphone workaround that circulates for
  # this family: that is for the Book4/Book5 (Meteor/Lunar Lake) DMIC path.
  # Raptor Lake Book3 uses the ALC298 analog mic.
  security.rtkit.enable = true;
  # pipewire itself (alsa/pulse/wireplumber) is enabled in the shared file.
  services.pipewire.alsa.support32Bit = true;

  # ---------------------------------------------------------------------------
  # Webcam -- Intel IPU6 (ipu6ep) + ov02c10 sensor via int3472/tps68470
  # ---------------------------------------------------------------------------
  # platform = "ipu6ep" is the correct value: the nixpkgs module documents
  # "ipu6" for Tiger Lake, "ipu6ep" for Alder Lake OR RAPTOR LAKE, and
  # "ipu6epmtl" for Meteor Lake. This is Raptor Lake-P.
  #
  # DECISION: OFF, and it stays off. Backlogged as its own project, not a
  # loose end in this install. The research, so future-you does not redo it:
  #
  #  * The camera is broken at the SENSOR, not here. Measured on this machine:
  #      ov02c10 i2c-OVTI02C1:00: error -EINVAL: external clock 26000000 is not supported
  #    The board clocks ov02c10 at 26 MHz; the in-tree driver demands 19.2 MHz
  #    and refuses to probe. The IPU6 itself is fine ("Connected 1 cameras").
  #    Enabling hardware.ipu6 does not address this.
  #  * There is NO nixpkgs or nixos-hardware option that fixes it. Specifically,
  #    `hardware.samsungGalaxyBook.ov02c10ClockFix` DOES NOT EXIST -- it is
  #    frequently misremembered. nixos-hardware has no Galaxy Book 3 entry at
  #    all (only samsung/np900x3c). Both checked directly. Do not go looking.
  #  * The only avenue is Intel's out-of-tree ipu6-drivers, which ships its own
  #    ov02c10.c. At the revision nixpkgs pins it defines OV02C10_MCLK=19200000
  #    but never compares the clock against it, so it should at least probe --
  #    whether its PLL setup is correct at 26 MHz is unproven.
  #  * The cost of trying: that package's `psys` module has an open upstream
  #    report (intel/ipu6-drivers#381) of s2idle freezing on kernels >= 6.16.
  #    We are on 6.18 and working sleep is a hard requirement. Not worth it for
  #    a camera that probably still would not produce a usable image.
  #
  # If you do pick this up: flip enable to true, rebuild, then check `dmesg |
  # grep ov02c10`, `v4l2-ctl --list-devices` (want /dev/video50), and crucially
  # `systemctl suspend` -- confirm it WAKES. Flipping back is the whole rollback;
  # nothing here is baked in at install time.
  hardware.ipu6 = {
    enable = false;
    platform = "ipu6ep";
  };

  # ---------------------------------------------------------------------------
  # Thunderbolt 4 / USB4
  # ---------------------------------------------------------------------------
  services.hardware.bolt.enable = true;

  # ---------------------------------------------------------------------------
  # TPM 2.0
  # ---------------------------------------------------------------------------
  # Present and usable; Secure Boot is disabled, so nothing here is load-bearing
  # for boot. This just makes the chip available to userspace (tpm2-tools etc.).
  # No LUKS key is sealed to it -- the disk is unlocked by passphrase.
  security.tpm2 = {
    enable = true;
    pkcs11.enable = true;
    tctiEnvironment.enable = true;
  };

  # ---------------------------------------------------------------------------
  # Laptop power management
  # ---------------------------------------------------------------------------
  # power-profiles-daemon rather than TLP: the samsung_galaxybook driver exposes
  # a real ACPI platform_profile (observed choices: low-power, quiet, balanced,
  # performance) and PPD drives that directly. The two conflict; do not enable
  # both.
  powerManagement.enable = true;
  services.power-profiles-daemon.enable = true;
  services.thermald.enable = true; # Intel thermal daemon, RAPL/DPTF
  services.upower.enable = true;
  services.fwupd.enable = true; # BIOS P07RGU.330.240529.ZQ; LVFS may have newer
  services.libinput.enable = true;

  # samsung_galaxybook also gives you, once booted:
  #   /sys/class/leds/samsung-galaxybook::kbd_backlight
  #   /sys/class/power_supply/BAT*/charge_control_end_threshold   (charge limit)
  #   /sys/firmware/acpi/platform_profile
  # All three were confirmed present on the target. No module parameters, no
  # acpi_osi override and no acpi_call shim are needed -- just the >=6.15 kernel
  # forced above. (The mainline driver has no module_param at all; the
  # kbd_backlight/performance_mode/battery_threshold parameters people quote
  # belong to the pre-6.14 out-of-tree branch and are a no-op here.)

  # ---------------------------------------------------------------------------
  # Shared-data subvolume (@nomad)
  # ---------------------------------------------------------------------------
  # ./disko.nix mounts the @nomad subvolume at /nomad. It is created root-owned;
  # give maddev a place inside it to own.
  #
  # Reminder: "nomad" here is the name of the data subvolume that travels
  # between NixOS and CachyOS. It is NOT related to hosts/nomad/ in this flake,
  # which is a different machine belonging to a different user.
  systemd.tmpfiles.rules = [
    "d /nomad 0755 root root -"
    "d /nomad/maddev 0700 maddev users -"
  ]
  ++ map (src: "d ${src} 0700 maddev users -") (lib.attrValues nomadBinds);

  # Bind the shared directories into $HOME so applications (Obsidian, Zen,
  # syncthing) see their usual paths while the bytes live on @nomad.
  #
  # `nofail` is deliberate: on a freshly installed system the sources do not
  # exist yet, and a missing bind mount must not wedge the boot. systemd-tmpfiles
  # creates them on first boot and they mount from the second boot onwards, or
  # immediately once the migration has put data there.
  fileSystems = lib.mapAttrs (_target: src: {
    device = src;
    fsType = "none";
    # `depends` is NixOS's own ordering knob: it makes the generated mount unit
    # require /nomad, which is where the source actually lives.
    depends = [ "/nomad" ];
    options = [
      "bind"
      "nofail"
    ];
  }) nomadBinds;

  # ---------------------------------------------------------------------------
  # Services carried over from the old smalltop
  # ---------------------------------------------------------------------------
  # Tailscale: bigsys is currently logged out, so there is no state to migrate.
  # This host just needs a fresh `tailscale up` after the install.
  services.tailscale.enable = true;

  # Syncthing.
  #
  # DO NOT copy bigsys's syncthing state onto this machine. The device ID IS the
  # identity -- two machines answering to one ID will fight. Leaving configDir
  # empty of a certificate lets syncthing generate a FRESH ID on first start;
  # that new ID then has to be introduced to the peers below by hand (or via an
  # introducer).
  #
  # Equally: do not rsync the vaults. Both folders already exist on other peers
  # (ObsidianVault on 8 devices, molten-river-knowledge on 2), so the correct
  # migration is to let syncthing replicate them. molten-river-knowledge having
  # only two replicas is the fragile one -- getting smalltop onto it is a net
  # increase in safety.
  #
  # overrideDevices/overrideFolders are false so that anything added later
  # through the web UI is not wiped on the next rebuild.
  #
  # Paths live under /nomad/maddev so CachyOS sees the same data; the
  # nomadBinds table at the top of this file bind-mounts them back into $HOME,
  # so ~/Knowledge and /nomad/maddev/Knowledge are the same directory.
  services.syncthing = {
    enable = true;
    user = "maddev";
    group = "users";
    dataDir = "/nomad/maddev/Knowledge";
    configDir = "/home/maddev/.local/state/syncthing";
    overrideDevices = false;
    overrideFolders = false;
    settings = {
      devices = {
        # Public device IDs. These are public keys, not secrets.
        Atmosphere.id = "LL7CJ3D-K2VWQWT-7XBOO6E-5ZCH3BP-PAMMOI2-TM3BX74-DSP4UX5-WAM6KQJ";
        WorkPC.id = "MUXVN5R-FEXPENP-4XNQPG7-XHCQEUH-E6MYV74-LQFFMMZ-ED3IBRT-RJALVQC";
        FairCaly.id = "M555SO5-7CSX6PN-GHNILWD-7Q7MW4R-DRJUIB4-WYOOMUH-NRIYBZK-PMYRIA5";
        bigsys.id = "NLGFRBA-4I2FD36-BF57YFJ-VUPZOKS-2TJHSUC-N7Z37J4-AQ73CRV-UMZ7FA6";
        blanket.id = "OFVY5ZC-EEZD2RI-NV3YFUD-I64ALWY-FY6FYUK-W62IINS-YWAOZW2-4SL6GQE";
        androidmoto.id = "W2DN3FF-YRPMIEO-XV2HOYB-ZQSCP3T-EJH3OIC-Y7WDC3N-EJSBFST-4FUL3AQ";
        madsystem-skandal.id = "ZTX4L66-KQSPHNX-J2OVFZT-3BFEDHL-E47MEM6-N4XGPAJ-MYLMKTC-CFFONQC";
        FP5.id = "4MQOIMD-JX4EUOA-ZF7ONSM-ZKBBDHX-PAT37XD-EBQEQFC-4Y2DCIU-PFZK3QG";
      };
      folders = {
        # Folder IDs must match the peers' exactly or nothing pairs up.
        "ObsidianVault" = {
          id = "ObsidianVault";
          label = "ObsidianVault";
          path = "/nomad/maddev/Knowledge/ObsidianVault";
          type = "sendreceive";
          devices = [
            "Atmosphere"
            "WorkPC"
            "FairCaly"
            "bigsys"
            "blanket"
            "androidmoto"
            "madsystem-skandal"
            "FP5"
          ];
        };
        "molten-river-knowledge" = {
          id = "molten-river-knowledge";
          path = "/nomad/maddev/Knowledge/molten-river/knowledge-backups";
          type = "sendreceive";
          devices = [
            "Atmosphere"
            "bigsys"
          ];
        };
      };
    };
  };

  # Theme overrides: the shared file sets tela/colorful_loop, maddev wants
  # whitesur/pixels on their machines.
  boot.loader.grub2-theme.theme = lib.mkForce "whitesur";
  boot.plymouth.theme = lib.mkForce "pixels";
  boot.plymouth.themePackages = lib.mkForce (
    with pkgs;
    [
      (adi1090x-plymouth-themes.override {
        selected_themes = [ "pixels" ];
      })
    ]
  );

  users.users.maddev = {
    isNormalUser = true;
    # Pinned rather than left to the allocator. Files on @nomad are seen by
    # CachyOS too, and a bind mount does not translate ownership -- if the two
    # systems disagree about maddev's uid, every shared file shows up owned by a
    # stranger. See CACHYOS.md.
    uid = 1000;
    description = "maddev";
    extraGroups = [
      "networkmanager"
      "wheel"
      "video"
      "input"
      "tss" # TPM2 access
    ];
    packages = with pkgs; [ ];
    shell = pkgs.zsh;
  };

  environment.systemPackages = with pkgs; [
    # Hardware poking, all read-only by default.
    pciutils
    usbutils
    nvme-cli
    btrfs-progs
    cryptsetup
    lvm2
    alsa-utils # aplay -l, amixer, speaker-test for the audio check above
    v4l-utils # v4l2-ctl --list-devices for the camera check above
    iw # iw reg get, to confirm the ES regdomain took
    powertop
    tpm2-tools
  ];
}
