#Windowrules customised accordingly
windowrule = opaque 1, match:class (jetbrains-studio|jetbrains-rustrover|scrcpy)
windowrule = opacity 1, match:class (firefox)
windowrule = rounding 3, match:class (firefox)
windowrule = workspace 3 silent, match:class ^(vesktop)$
windowrule = float 1, match:class ^(com.github.neithern.g4music|org.qbittorrent.qBittorrent)$
windowrule = float 1, match:class ^(it.mijorus.smile)
windowrule = float 1, match:class ^(xdg-desktop-portal-gtk)$
windowrule = stay_focused 1, match:class (pinentry-)
windowrule = no_initial_focus 1, match:class ^(.*jetbrains.*)$, match:title ^(win.*)$
windowrule = stay_focused 1, match:class ^(.*jetbrains.*)$, match:title ^$, match:float 1
windowrule = no_initial_focus 1, match:class ^(.*jetbrains.*)$, match:title ^\s$
windowrule = tile 1, match:class ^(jetbrains-*), match:float 0

#Picture-in-Picture special treatment
windowrule = float 1, match:title (Picture-in-Picture)
windowrule = size 585 330, match:title (Picture-in-Picture)
windowrule = move (monitor_w-816) 50, match:title (Picture-in-Picture)
windowrule = pin 1, match:title (Picture-in-Picture)
windowrule = no_dim 1, match:title (Picture-in-Picture)
windowrule = opacity 1 0.8, match:title (Picture-in-Picture)
windowrule = no_initial_focus 1, match:title (Picture-in-Picture)
windowrule = opacity 1, match:title (Picture-in-Picture), match:float 0

#layerrules
layerrule = blur 1, match:namespace waybar
layerrule = blur 1, match:namespace logout_dialog
layerrule = blur 1, ignore_alpha 0, match:namespace rofi
layerrule = blur 1, ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = blur 1, ignore_alpha 0.5, match:namespace swaync-notification-window
