# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.systemd.enable = true;
  boot.initrd.verbose = true;
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "loglevel=7" "systemd.log_level=debug" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cb648434-8a64-45b2-bf43-928c1e904d0e";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a6919d29-d1f9-4b98-b57f-251be8c456c9".device =
    "/dev/disk/by-uuid/a6919d29-d1f9-4b98-b57f-251be8c456c9";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A39B-8DED";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
